### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by agarnitin86** [ruidan/Unsupervised-Aspect-Extraction#17]
I am using gensim 0.12.4 on python 3 and still getting the following error

Traceback (most recent call last):

  File "<ipython-input-10-b654e0831319>", line 1, in <module>
    model = create_model(ortho_reg, neg_size, emb_dim, aspect_size, emb_path, overall_maxlen, vocab)

  File "/home/fractaluser/Projects/workspace/UnsupervisedAspectExtraction/code/model.py", line 63, in create_model
    emb_reader = EmbReader(emb_path, emb_dim=emb_dim)

  File "/home/fractaluser/Projects/workspace/UnsupervisedAspectExtraction/code/w2v_emb_reader.py", line 23, in __init__
    model = gensim.models.Word2Vec.load(emb_path)

  File "/home/fractaluser/anaconda3/envs/venv_keras/lib/python3.5/site-packages/gensim/models/word2vec.py", line 1485, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)

  File "/home/fractaluser/anaconda3/envs/venv_keras/lib/python3.5/site-packages/gensim/utils.py", line 248, in load
    obj = unpickle(fname)

  File "/home/fractaluser/anaconda3/envs/venv_keras/lib/python3.5/site-packages/gensim/utils.py", line 912, in unpickle
    return _pickle.loads(f.read())

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 0: ordinal not in range(128)

**Comment by pati-dev** [comment]
I'm getting the same error. Is there any fix available for this?
