### ISSUE TITLE
Dependencies errors

### ISSUE THREAD

**Issue by BrambleXu** [ruidan/Unsupervised-Aspect-Extraction#5]
I run the run_script.sh with a GPU machine, but get the error message below
It seems the cuda version is not suitable. So which cuda version should be used?

```
Using Theano backend.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

2018-05-30 01:28:42,026 WARNING The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GRID K520 (CNMeM is disabled, cuDNN not available)
Traceback (most recent call last):
  File "train.py", line 50, in <module>
    from keras.preprocessing import sequence
  File "/home/ubuntu/miniconda3/envs/py27/lib/python2.7/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/home/ubuntu/miniconda3/envs/py27/lib/python2.7/site-packages/keras/backend/__init__.py", line 64, in <module>
    from .theano_backend import *
  File "/home/ubuntu/miniconda3/envs/py27/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 1, in <module>
    import theano
  File "/home/ubuntu/miniconda3/envs/py27/lib/python2.7/site-packages/theano/__init__.py", line 116, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/home/ubuntu/miniconda3/envs/py27/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 41, in test_nvidia_driver1
    raise Exception("The nvidia driver version installed with this OS "
Exception: The nvidia driver version installed with this OS does not give good results for reduction.Installing the nvidia driver available on the same download page as the cuda package will fix the problem: http://developer.nvidia.com/cuda-downloads
```

And if I use the CPU to train, there are also some log info:
```
2018-05-30 10:43:44,656 INFO Pattern library is not installed, lemmatization won't be available.
2018-05-30 10:43:44,892 INFO 'pattern' package not found; tag filters are not available for English
```
What is the Pattern library. And I can not find where these log info are writen in the python file. It seems in the utils.py. 

Beside this, I also got errors that tell me there are no module named pygpu and h5py.
What are the version of pygpu and h5py?

**Comment by ruidan** [comment]
In my experiments I used cudnn 5.1. You can also change the backend to theano 1.0.1, which is compatible with cuda 8.0 and cudnn 6.0

**Comment by BrambleXu** [comment]
@ruidan Thanks for the information. During the train, two log information showed up. Did you know want is the pattern library? It seems related with lemmatization and tag filters.

```
2018-05-30 10:43:44,656 INFO Pattern library is not installed, lemmatization won't be available.
2018-05-30 10:43:44,892 INFO 'pattern' package not found; tag filters are not available for English
```

**Comment by BrambleXu** [comment]
@hustlrr gensim version is 0.12.4, you can find it [here](https://github.com/ruidan/Unsupervised-Aspect-Extraction/issues/3)

**Comment by ruidan** [comment]
@BrambleXu Is that just a warning? Can you run the script successfully?

**Comment by BrambleXu** [comment]
@ruidan  Yes, it is just a warning. The script runs successfully.

**Comment by ruidan** [comment]
@BrambleXu I think that doesn't affect the results. You can just ignore it.

**Comment by BrambleXu** [comment]
@ruidan Gotcha. Thanks.
